version: '3.4'
services:
  sourced-ui:
    # run container as root instead of superset user defined in Dockerfile
    user: 0:0
    image: srcd/sourced-ui:latest-dev
    volumes:
      - type: bind
        source: ${SOURCED_UI_ABS_PATH}/superset/superset
        target: /home/superset/superset
        consistency: delegated
      - ${SOURCED_UI_ABS_PATH}/superset/dashboards:/home/superset/dashboards
      - ${SOURCED_UI_ABS_PATH}/superset/contrib/docker/superset_config.py:/home/superset/superset/superset_config.py
      - ${SOURCED_UI_ABS_PATH}/superset/contrib/docker/docker-entrypoint.sh:/entrypoint.sh
      - type: volume
        source: node_modules
        target: /home/superset/superset/assets/node_modules
    environment:
      SUPERSET_ENV: development
      LOCAL_USER: ${LOCAL_USER:-}

  sourced-ui-celery:
    # disable separate celery container
    image: tianon/true
    entrypoint: 'true'
    command: 'true'

volumes:
  node_modules:
    external: false
